### YamlMime:ManagedReference
apiRules:
  - exclude:
      uidRegex: "^.*\\.[^.]*Name$"  # Excludes all subclasses ending in 'Name'
      type: "Class"
  - exclude:
      uidRegex: "^GodotPlugins\\."
      type: "Class"
